---
# Ansible Galaxy requirements
# Install with: ansible-galaxy install -r requirements.yml

roles: []
  # - name: geerlingguy.docker
  #   version: 4.1.0
  # - name: geerlingguy.postgresql
  #   version: 3.4.0

collections: []
  # - name: community.general
  #   version: '>=5.0.0'
  # - name: ansible.posix
  #   version: '>=1.4.0'
  # - name: community.docker
  #   version: '>=3.0.0'
