---
# Debian family specific tasks (Debian, Ubuntu)

- name: (debian) Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags:
    - auto-updates
    - install

- name: (debian) Install unattended-upgrades package
  package:
    name: 
      - unattended-upgrades
      - apt-listchanges
    state: present
  tags:
    - auto-updates
    - install

- name: (debian) Create systemd override directory for apt-daily timer
  file:
    path: /etc/systemd/system/apt-daily.timer.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - auto-updates
    - config

- name: (debian) Normalize update_exclude_packages to list
  set_fact:
    update_exclude_packages_list: >-
      {{
        update_exclude_packages if update_exclude_packages is sequence and update_exclude_packages is not string
        else [update_exclude_packages] if update_exclude_packages is string and update_exclude_packages != ""
        else update_exclude_packages.split(',') if update_exclude_packages is string and ',' in update_exclude_packages
        else []
      }}
  tags:
    - auto-updates
    - config

- name: (debian) Configure automatic updates
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - restart unattended-upgrades
  tags:
    - auto-updates
    - config

- name: (debian) Configure unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - restart unattended-upgrades
  tags:
    - auto-updates
    - config

- name: (debian) Configure apt-daily timer schedule
  copy:
    content: |
      [Timer]
      OnCalendar=
      OnCalendar=*-*-* {{ update_schedule }}:00
      RandomizedDelaySec=0
      Persistent=true
      
      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/apt-daily.timer.d/override.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - reload systemd
    - restart apt-daily-timer
  tags:
    - auto-updates
    - schedule

- name: (debian) Enable and start unattended-upgrades service
  systemd:
    name: unattended-upgrades
    enabled: true
    state: started
    daemon_reload: true
  when: auto_updates_enabled | bool
  tags:
    - auto-updates
    - service

- name: (debian) Enable and start apt-daily timer
  systemd:
    name: apt-daily.timer
    enabled: true
    state: started
    daemon_reload: true
  when: auto_updates_enabled | bool
  tags:
    - auto-updates
    - service

- name: (debian) Disable services when updates disabled
  systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - unattended-upgrades
    - apt-daily.timer
  when: not (auto_updates_enabled | bool)
  tags:
    - auto-updates
    - service

- name: (debian) Set service name for verification
  set_fact:
    auto_updates_service_name: "unattended-upgrades"