---
# tasks file for roles/automatic-updates
- name: (main) Debug detected OS family
  debug:
    msg: "Detected OS family: {{ ansible_os_family }}, Distribution: {{ ansible_distribution }}"
  tags:
    - auto-updates
    - debug

- name: (main) Handle RedHat family tasks with fallback
  block:
    - name: (main) Include RedHat family tasks
      include_tasks: redhat.yml
      when: ansible_os_family == "RedHat"
  rescue:
    - name: (main) Try RedHat fallback installation method
      include_tasks: redhat-fallback.yml
      when: ansible_os_family == "RedHat"
  when: ansible_os_family == "RedHat"
  tags:
    - auto-updates
    - redhat

- name: (main) Include Debian family tasks
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - auto-updates
    - debian

- name: (main) Include SUSE family tasks
  include_tasks: suse.yml
  when: ansible_os_family == "Suse"
  tags:
    - auto-updates
    - suse

- name: (main) Verify automatic updates service status
  service:
    name: "{{ auto_updates_service_name }}"
    state: started
    enabled: true
  when: 
    - auto_updates_service_name is defined
    - auto_updates_enabled | bool
  tags:
    - auto-updates
    - verify