---
# RedHat family specific tasks (RHEL, CentOS, AlmaLinux, OracleLinux)

- name: (redhat) Install dnf-automatic package with fallback handling
  block:
    - name: (redhat) Check current DNF exclusions
      shell: dnf config-manager --dump | grep -E '^exclude\s*=' || echo "exclude="
      register: current_dnf_excludes
      changed_when: false
      failed_when: false
      tags:
        - auto-updates
        - install

    - name: (redhat) Temporarily disable dnf-automatic exclusion for installation
      lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^exclude='
        line: "exclude={{ current_dnf_excludes.stdout.split('=')[1] | regex_replace('dnf-automatic[*]?', '') | regex_replace('\\s+', ' ') | trim }}"
        backup: true
      when: 
        - current_dnf_excludes.stdout is defined
        - "'dnf-automatic' in current_dnf_excludes.stdout"
      register: temporary_exclude_change

    - name: (redhat) Install dnf-automatic package
      package:
        name: dnf-automatic
        state: present
        disable_excludes: all

    - name: (redhat) Restore original DNF exclusions after installation
      lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^exclude='
        line: "{{ current_dnf_excludes.stdout }}"
        backup: true
      when: temporary_exclude_change is defined and temporary_exclude_change.changed

  rescue:
    - name: (redhat) Try installing dnf-automatic with yum (fallback)
      yum:
        name: dnf-automatic
        state: present
        disable_excludes: all
      when: ansible_pkg_mgr == "yum"
      ignore_errors: true

    - name: (redhat) Install dnf-automatic using rpm (last resort)
      shell: |
        dnf download dnf-automatic --downloadonly --downloaddir=/tmp/
        rpm -Uvh --force /tmp/dnf-automatic*.rpm
        rm -f /tmp/dnf-automatic*.rpm
      args:
        creates: /usr/bin/dnf-automatic
      when: ansible_pkg_mgr == "dnf"
      ignore_errors: true

  tags:
    - auto-updates
    - install

- name: (redhat) Create systemd override directory for dnf-automatic timer
  file:
    path: /etc/systemd/system/dnf-automatic.timer.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - auto-updates
    - config

- name: (redhat) Configure dnf-automatic
  template:
    src: dnf-automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - restart dnf-automatic
  tags:
    - auto-updates
    - config

- name: (redhat) Normalize update_exclude_packages to list
  set_fact:
    update_exclude_packages_list: >-
      {{
        update_exclude_packages if update_exclude_packages is sequence and update_exclude_packages is not string
        else [update_exclude_packages] if update_exclude_packages is string and update_exclude_packages != ""
        else update_exclude_packages.split(',') if update_exclude_packages is string and ',' in update_exclude_packages
        else []
      }}
  tags:
    - auto-updates
    - config

- name: (redhat) Get current exclusions from dnf.conf
  set_fact:
    current_excludes_list: >-
      {{
        current_dnf_excludes.stdout.split('=')[1].split() if current_dnf_excludes.stdout is defined and current_dnf_excludes.stdout != "exclude="
        else []
      }}
  tags:
    - auto-updates
    - config

- name: (redhat) Configure package exclusions in dnf.conf
  lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^exclude='
    line: "exclude={{ (current_excludes_list + update_exclude_packages_list) | unique | join(' ') }}"
    state: present
    backup: true
  when: 
    - update_exclude_packages_list is defined
    - update_exclude_packages_list | length > 0
  tags:
    - auto-updates
    - config

- name: (redhat) Remove package exclusions from dnf.conf when no exclusions defined
  lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^exclude='
    state: absent
    backup: true
  when: 
    - update_exclude_packages_list is not defined or update_exclude_packages_list | length == 0
    - current_excludes_list is not defined or current_excludes_list | length == 0
  tags:
    - auto-updates
    - config

- name: (redhat) Configure dnf-automatic timer schedule
  copy:
    content: |
      [Timer]
      OnCalendar=
      OnCalendar=*-*-* {{ update_schedule }}:00
      RandomizedDelaySec=0
      Persistent=true
      
      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/dnf-automatic.timer.d/override.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - reload systemd
    - restart dnf-automatic-timer
  tags:
    - auto-updates
    - schedule

- name: (redhat) Enable and start dnf-automatic timer
  systemd:
    name: dnf-automatic.timer
    enabled: true
    state: started
    daemon_reload: true
  when: auto_updates_enabled | bool
  tags:
    - auto-updates
    - service

- name: (redhat) Disable dnf-automatic timer when updates disabled
  systemd:
    name: dnf-automatic.timer
    enabled: false
    state: stopped
  when: not (auto_updates_enabled | bool)
  tags:
    - auto-updates
    - service

- name: (redhat) Set service name for verification
  set_fact:
    auto_updates_service_name: "dnf-automatic.timer"