---
# SUSE family specific tasks (openSUSE)
- name: (suse) Install automatic updates packages
  package:
    name:
      - zypper
      - cron
    state: present
  tags:
    - auto-updates
    - install

- name: (suse) Configure zypper automatic updates exclusions
  lineinfile:
    path: /etc/zypp/zypp.conf
    regexp: '^solver.onlyRequires'
    line: "solver.onlyRequires = true"
    backup: true
  when: update_exclude_packages is defined and update_exclude_packages | length > 0
  tags:
    - auto-updates
    - config

- name: (suse) Create zypper automatic update script
  template:
    src: zypper-auto-update.sh.j2
    dest: /usr/local/bin/zypper-auto-update.sh
    owner: root
    group: root
    mode: '0755'
    backup: true
  tags:
    - auto-updates
    - config

- name: (suse) Configure cron job for automatic updates
  cron:
    name: "Automatic zypper updates"
    minute: "0"
    hour: "{{ update_schedule.split(':')[0] }}"
    job: "/usr/local/bin/zypper-auto-update.sh"
    user: root
    state: "{{ 'present' if auto_updates_enabled else 'absent' }}"
  tags:
    - auto-updates
    - schedule

- name: (suse) Enable and start cron service
  systemd:
    name: cron
    enabled: true
    state: started
  when: auto_updates_enabled | bool
  tags:
    - auto-updates
    - service

- name: (suse) Set service name for verification
  set_fact:
    auto_updates_service_name: "cron"