---
# Development inventory
all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 192.168.1.10
        web02:
          ansible_host: 192.168.1.11
    databases:
      hosts:
        db01:
          ansible_host: 192.168.1.20
          postgresql_version: 14
    appservers:
      hosts:
        app01:
          ansible_host: 192.168.1.30
        app02:
          ansible_host: 192.168.1.31
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    environment: development
